NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 0.878
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_G = 0.509
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 0.509
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 0.862
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 0.321
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 0.321